### ISSUE TITLE
http://wiki.midibox.org

### ISSUE THREAD

**Issue by yzqzss** [saveweb/dokuwiki-archive-project#5]

**Comment by yzqzss** [comment]
@robkam Have you uploaded this wiki to IA?

**Comment by robkam** [comment]
at https://archive.org/details/wiki.midibox.2023.02.18
I don't know how easy/difficult it is to find the archive on IA

**Comment by yzqzss** [comment]
https://archive.org/details/wiki.midibox.org-20230323
